-- 128 perguntas USCIS — formato 2025 (revisado)
INSERT INTO public.civics_questions (question, answers, category, format) VALUES

-- PRINCIPLES OF DEMOCRACY
('What is the supreme law of the land?', ARRAY['the Constitution'], 'principles_of_democracy', '2025'),
('What does the Constitution do?', ARRAY['sets up the government', 'defines the government', 'protects basic rights of Americans'], 'principles_of_democracy', '2025'),
('The idea of self-government is in the first three words of the Constitution. What are these words?', ARRAY['We the People'], 'principles_of_democracy', '2025'),
('What is an amendment?', ARRAY['a change (to the Constitution)', 'an addition (to the Constitution)'], 'principles_of_democracy', '2025'),
('What do we call the first ten amendments to the Constitution?', ARRAY['the Bill of Rights'], 'principles_of_democracy', '2025'),
('What is one right or freedom from the First Amendment?', ARRAY['speech', 'religion', 'assembly', 'press', 'petition the government'], 'principles_of_democracy', '2025'),
('How many amendments does the Constitution have?', ARRAY['twenty-seven (27)'], 'principles_of_democracy', '2025'),
('What did the Declaration of Independence do?', ARRAY['announced our independence (from Great Britain)', 'declared our independence (from Great Britain)', 'said that the United States is free (from Great Britain)'], 'principles_of_democracy', '2025'),
('What are two rights in the Declaration of Independence?', ARRAY['life and liberty', 'liberty and the pursuit of happiness', 'life and the pursuit of happiness'], 'principles_of_democracy', '2025'),
('What is freedom of religion?', ARRAY['You can practice any religion, or not practice a religion.'], 'principles_of_democracy', '2025'),
('What is the economic system in the United States?', ARRAY['capitalist economy', 'market economy'], 'principles_of_democracy', '2025'),
('What is the "rule of law"?', ARRAY['Everyone must follow the law.', 'Leaders must obey the law.', 'Government must obey the law.', 'No one is above the law.'], 'principles_of_democracy', '2025'),
('Name one important idea from the Declaration of Independence.', ARRAY['all people are created equal', 'basic rights are protected by the government', 'the right to change or abolish an abusive government'], 'principles_of_democracy', '2025'),
('What does "freedom of the press" mean?', ARRAY['The media (newspapers, TV, radio) can report news without government control.'], 'principles_of_democracy', '2025'),
('What are "inalienable rights"?', ARRAY['individual rights that people are born with', 'rights that cannot be taken away'], 'principles_of_democracy', '2025'),
('What document declared our independence from Great Britain?', ARRAY['the Declaration of Independence'], 'principles_of_democracy', '2025'),

-- SYSTEM OF GOVERNMENT
('Name one branch or part of the government.', ARRAY['Congress', 'legislative', 'President', 'executive', 'the courts', 'judicial'], 'system_of_government', '2025'),
('What stops one branch of government from becoming too powerful?', ARRAY['checks and balances', 'separation of powers'], 'system_of_government', '2025'),
('Who is in charge of the executive branch?', ARRAY['the President'], 'system_of_government', '2025'),
('Who makes federal laws?', ARRAY['Congress', 'Senate and House (of Representatives)', '(U.S. or national) legislature'], 'system_of_government', '2025'),
('What are the two parts of the U.S. Congress?', ARRAY['the Senate and House (of Representatives)'], 'system_of_government', '2025'),
('How many U.S. Senators are there?', ARRAY['one hundred (100)'], 'system_of_government', '2025'),
('We elect a U.S. Senator for how many years?', ARRAY['six (6)'], 'system_of_government', '2025'),
('Who is one of your state''s U.S. Senators now?', ARRAY['Answers will vary. Acceptable answers include the current U.S. Senators for the applicant''s state.'], 'system_of_government', '2025'),
('The House of Representatives has how many voting members?', ARRAY['four hundred thirty-five (435)'], 'system_of_government', '2025'),
('We elect a U.S. Representative for how many years?', ARRAY['two (2)'], 'system_of_government', '2025'),
('Name your U.S. Representative.', ARRAY['Answers will vary. Acceptable answers include the current U.S. Representative for the applicant''s district.'], 'system_of_government', '2025'),
('Who does a U.S. Senator represent?', ARRAY['all people of the state'], 'system_of_government', '2025'),
('Why do some states have more Representatives than other states?', ARRAY['(because of) the state''s population', '(because) they have more people', '(because) some states have more people'], 'system_of_government', '2025'),
('We elect a President for how many years?', ARRAY['four (4)'], 'system_of_government', '2025'),
('In what month do we vote for President?', ARRAY['November'], 'system_of_government', '2025'),
('What is the name of the President of the United States now?', ARRAY['Joe Biden', 'Biden'], 'system_of_government', '2025'),
('What is the name of the Vice President of the United States now?', ARRAY['Kamala Harris', 'Harris'], 'system_of_government', '2025'),
('If the President can no longer serve, who becomes President?', ARRAY['the Vice President'], 'system_of_government', '2025'),
('If both the President and the Vice President can no longer serve, who becomes President?', ARRAY['the Speaker of the House'], 'system_of_government', '2025'),
('Who is the Commander in Chief of the military?', ARRAY['the President'], 'system_of_government', '2025'),
('Who signs bills to become laws?', ARRAY['the President'], 'system_of_government', '2025'),
('Who vetoes bills?', ARRAY['the President'], 'system_of_government', '2025'),
('What does the President''s Cabinet do?', ARRAY['advises the President'], 'system_of_government', '2025'),
('What are two Cabinet-level positions?', ARRAY['Secretary of Agriculture', 'Secretary of Commerce', 'Secretary of Defense', 'Secretary of Education', 'Secretary of Energy', 'Secretary of Health and Human Services', 'Secretary of Homeland Security', 'Secretary of Housing and Urban Development', 'Secretary of the Interior', 'Secretary of Labor', 'Secretary of State', 'Secretary of Transportation', 'Secretary of the Treasury', 'Secretary of Veterans Affairs', 'Attorney General', 'Vice President'], 'system_of_government', '2025'),
('What does the judicial branch do?', ARRAY['reviews laws', 'explains laws', 'resolves disputes (disagreements)', 'decides if a law goes against the Constitution'], 'system_of_government', '2025'),
('What is the highest court in the United States?', ARRAY['the Supreme Court'], 'system_of_government', '2025'),
('How many justices are on the Supreme Court?', ARRAY['nine (9)'], 'system_of_government', '2025'),
('Who is the Chief Justice of the United States now?', ARRAY['John Roberts', 'John G. Roberts, Jr.'], 'system_of_government', '2025'),
('Under our Constitution, some powers belong to the federal government. What is one power of the federal government?', ARRAY['to print money', 'to declare war', 'to create an army', 'to make treaties'], 'system_of_government', '2025'),
('Under our Constitution, some powers belong to the states. What is one power of the states?', ARRAY['provide schooling and education', 'provide protection (police)', 'provide safety (fire departments)', 'give a driver''s license', 'approve zoning and land use'], 'system_of_government', '2025'),
('Who is the Governor of your state now?', ARRAY['Answers will vary. Acceptable answers include the current Governor of the applicant''s state.'], 'system_of_government', '2025'),
('What is the capital of your state?', ARRAY['Answers will vary. Acceptable answers include the current capital of the applicant''s state.'], 'system_of_government', '2025'),
('What are the two major political parties in the United States?', ARRAY['Democratic and Republican'], 'system_of_government', '2025'),
('What is the political party of the President now?', ARRAY['Democratic (Party)'], 'system_of_government', '2025'),
('What is the name of the Speaker of the House of Representatives now?', ARRAY['Mike Johnson'], 'system_of_government', '2025'),
('What is the Electoral College?', ARRAY['a process by which Americans elect the President', 'a group that elects the President'], 'system_of_government', '2025'),
('What are the duties of Congress?', ARRAY['writes laws', 'declares war', 'approves the budget'], 'system_of_government', '2025'),
('How are changes made to the Constitution?', ARRAY['through amendments'], 'system_of_government', '2025'),
('How long is a presidential term?', ARRAY['four (4) years'], 'system_of_government', '2025'),
('What limits the number of terms a President can serve?', ARRAY['the 22nd Amendment'], 'system_of_government', '2025'),
('What is the purpose of the United Nations?', ARRAY['to promote international cooperation', 'to maintain international peace and security'], 'system_of_government', '2025'),

-- RIGHTS AND RESPONSIBILITIES
('There are four amendments to the Constitution about who can vote. Describe one of them.', ARRAY['Citizens eighteen (18) and older (can vote).', 'You don''t have to pay (a poll tax) to vote.', 'Any citizen can vote. (Women and men can vote.)', 'A male citizen of any race (can vote).'], 'rights_and_responsibilities', '2025'),
('What is one responsibility that is only for United States citizens?', ARRAY['serve on a jury', 'vote in a federal election'], 'rights_and_responsibilities', '2025'),
('Name one right only for United States citizens.', ARRAY['vote in a federal election', 'run for federal office'], 'rights_and_responsibilities', '2025'),
('What are two rights of everyone living in the United States?', ARRAY['freedom of expression', 'freedom of speech', 'freedom of assembly', 'freedom to petition the government', 'freedom of religion', 'the right to bear arms'], 'rights_and_responsibilities', '2025'),
('What do we show loyalty to when we say the Pledge of Allegiance?', ARRAY['the United States', 'the flag'], 'rights_and_responsibilities', '2025'),
('What is one promise you make when you become a United States citizen?', ARRAY['give up loyalty to other countries', 'defend the Constitution and laws of the United States', 'obey the laws of the United States', 'serve in the U.S. military (if needed)', 'serve (do important work for) the nation (if needed)', 'be loyal to the United States'], 'rights_and_responsibilities', '2025'),
('How old do citizens have to be to vote for President?', ARRAY['eighteen (18) and older'], 'rights_and_responsibilities', '2025'),
('What are two ways that Americans can participate in their democracy?', ARRAY['vote', 'join a political party', 'help with a campaign', 'join a civic group', 'join a community group', 'give an elected official your opinion on an issue', 'call Senators and Representatives', 'publicly support or oppose an issue or policy', 'run for office', 'write to a newspaper'], 'rights_and_responsibilities', '2025'),
('When is the last day you can send in federal income tax forms?', ARRAY['April 15'], 'rights_and_responsibilities', '2025'),
('When must all men register for the Selective Service?', ARRAY['at age eighteen (18)', 'between eighteen (18) and twenty-six (26)'], 'rights_and_responsibilities', '2025'),
('What is the Pledge of Allegiance?', ARRAY['the promise of loyalty to the flag and the nation'], 'rights_and_responsibilities', '2025'),
('What is one right of everyone living in the United States?', ARRAY['freedom of speech', 'freedom of the press', 'freedom of religion', 'freedom to petition the government', 'freedom of assembly', 'the right to bear arms'], 'rights_and_responsibilities', '2025'),
('Name two national holidays in the United States.', ARRAY['New Year''s Day', 'Martin Luther King Jr. Day', 'Presidents'' Day', 'Memorial Day', 'Juneteenth', 'Independence Day', 'Labor Day', 'Columbus Day', 'Veterans Day', 'Thanksgiving', 'Christmas'], 'rights_and_responsibilities', '2025'),

-- COLONIAL PERIOD AND INDEPENDENCE
('What is one reason colonists came to America?', ARRAY['freedom', 'political liberty', 'religious freedom', 'economic opportunity', 'to practice their religion', 'to escape persecution'], 'colonial_period_and_independence', '2025'),
('Who lived in America before the Europeans arrived?', ARRAY['American Indians', 'Native Americans'], 'colonial_period_and_independence', '2025'),
('What group of people was taken to America and sold as slaves?', ARRAY['Africans', 'people from Africa'], 'colonial_period_and_independence', '2025'),
('Why did the colonists fight the British?', ARRAY['because of high taxes (taxation without representation)', 'because the British army stayed in their houses (boarding, quartering)', 'because they didn''t have self-government'], 'colonial_period_and_independence', '2025'),
('Who wrote the Declaration of Independence?', ARRAY['(Thomas) Jefferson'], 'colonial_period_and_independence', '2025'),
('When was the Declaration of Independence adopted?', ARRAY['July 4, 1776'], 'colonial_period_and_independence', '2025'),
('There were 13 original states. Name three.', ARRAY['New Hampshire', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New York', 'New Jersey', 'Pennsylvania', 'Delaware', 'Maryland', 'Virginia', 'North Carolina', 'South Carolina', 'Georgia'], 'colonial_period_and_independence', '2025'),
('What happened at the Constitutional Convention?', ARRAY['The Constitution was written.', 'The Founding Fathers wrote the Constitution.'], 'colonial_period_and_independence', '2025'),
('When was the Constitution written?', ARRAY['1787'], 'colonial_period_and_independence', '2025'),
('The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.', ARRAY['(James) Madison', '(Alexander) Hamilton', '(John) Jay', 'Publius'], 'colonial_period_and_independence', '2025'),
('What is one thing Benjamin Franklin is famous for?', ARRAY['U.S. diplomat', 'oldest member of the Constitutional Convention', 'first Postmaster General of the United States', 'writer of "Poor Richard''s Almanac"', 'started the first free libraries'], 'colonial_period_and_independence', '2025'),
('Who is the "Father of Our Country"?', ARRAY['(George) Washington'], 'colonial_period_and_independence', '2025'),
('Who was the first President?', ARRAY['(George) Washington'], 'colonial_period_and_independence', '2025'),
('Name one of the writers of the Federalist Papers.', ARRAY['(James) Madison', '(Alexander) Hamilton', '(John) Jay'], 'colonial_period_and_independence', '2025'),
('What was the main concern of the colonists before the Revolutionary War?', ARRAY['taxation without representation', 'lack of self-government'], 'colonial_period_and_independence', '2025'),

-- THE 1800s
('What territory did the United States buy from France in 1803?', ARRAY['the Louisiana Territory', 'Louisiana'], 'the_1800s', '2025'),
('Name one war fought by the United States in the 1800s.', ARRAY['War of 1812', 'Mexican-American War', 'Civil War', 'Spanish-American War'], 'the_1800s', '2025'),
('Name the U.S. war between the North and the South.', ARRAY['the Civil War', 'the War between the States'], 'the_1800s', '2025'),
('Name one problem that led to the Civil War.', ARRAY['slavery', 'economic reasons', 'states'' rights'], 'the_1800s', '2025'),
('What was one important thing that Abraham Lincoln did?', ARRAY['freed the slaves (Emancipation Proclamation)', 'saved (or preserved) the Union', 'led the United States during the Civil War'], 'the_1800s', '2025'),
('What did the Emancipation Proclamation do?', ARRAY['freed the slaves', 'freed slaves in the Confederacy', 'freed slaves in the Confederate states', 'freed slaves in most Southern states'], 'the_1800s', '2025'),
('What did Susan B. Anthony do?', ARRAY['fought for women''s rights', 'fought for civil rights'], 'the_1800s', '2025'),
('What was the Underground Railroad?', ARRAY['a system that helped enslaved people escape to freedom'], 'the_1800s', '2025'),
('What amendments address slavery and equal rights?', ARRAY['13th', '14th', '15th Amendments'], 'the_1800s', '2025'),
('What was the significance of the 13th Amendment?', ARRAY['abolished slavery', 'ended slavery in the United States'], 'the_1800s', '2025'),
('What was the significance of the 19th Amendment?', ARRAY['gave women the right to vote', 'women''s suffrage'], 'the_1800s', '2025'),

-- RECENT AMERICAN HISTORY
('Name one war fought by the United States in the 1900s.', ARRAY['World War I', 'World War II', 'Korean War', 'Vietnam War', '(Persian) Gulf War'], 'recent_american_history', '2025'),
('Who was President during World War I?', ARRAY['(Woodrow) Wilson'], 'recent_american_history', '2025'),
('Who was President during the Great Depression and World War II?', ARRAY['(Franklin) Roosevelt'], 'recent_american_history', '2025'),
('Who did the United States fight in World War II?', ARRAY['Japan, Germany, and Italy'], 'recent_american_history', '2025'),
('Before he was President, Eisenhower was a general. What war was he in?', ARRAY['World War II'], 'recent_american_history', '2025'),
('During the Cold War, what was the main concern of the United States?', ARRAY['Communism'], 'recent_american_history', '2025'),
('What movement tried to end racial discrimination?', ARRAY['civil rights (movement)'], 'recent_american_history', '2025'),
('What did Martin Luther King, Jr. do?', ARRAY['fought for civil rights', 'worked for equality for all Americans'], 'recent_american_history', '2025'),
('What major event happened on September 11, 2001, in the United States?', ARRAY['Terrorists attacked the United States.'], 'recent_american_history', '2025'),
('Name one American Indian tribe in the United States.', ARRAY['Cherokee', 'Navajo', 'Sioux', 'Chippewa', 'Choctaw', 'Pueblo', 'Apache', 'Iroquois', 'Creek', 'Blackfeet', 'Seminole', 'Cheyenne', 'Arawak', 'Shawnee', 'Mohegan', 'Huron', 'Oneida', 'Lakota', 'Crow', 'Teton', 'Hopi', 'Inuit'], 'recent_american_history', '2025'),
('What was the significance of Brown v. Board of Education?', ARRAY['ruled racial segregation in public schools unconstitutional', 'ended school segregation'], 'recent_american_history', '2025'),
('What was the Cold War?', ARRAY['tension between the United States and the Soviet Union', 'competition between democratic and communist nations'], 'recent_american_history', '2025'),
('Name one U.S. war fought after September 11, 2001.', ARRAY['War in Afghanistan', 'War in Iraq'], 'recent_american_history', '2025'),
('Name one reason Americans fought in the Korean War.', ARRAY['to stop the spread of Communism', 'to defend South Korea from North Korea'], 'recent_american_history', '2025'),

-- GEOGRAPHY
('Name one of the two longest rivers in the United States.', ARRAY['Missouri (River)', 'Mississippi (River)'], 'geography', '2025'),
('What ocean is on the West Coast of the United States?', ARRAY['Pacific (Ocean)'], 'geography', '2025'),
('What ocean is on the East Coast of the United States?', ARRAY['Atlantic (Ocean)'], 'geography', '2025'),
('Name one U.S. territory.', ARRAY['Puerto Rico', 'U.S. Virgin Islands', 'American Samoa', 'Northern Mariana Islands', 'Guam'], 'geography', '2025'),
('Name one state that borders Canada.', ARRAY['Maine', 'New Hampshire', 'Vermont', 'New York', 'Pennsylvania', 'Ohio', 'Michigan', 'Minnesota', 'North Dakota', 'Montana', 'Idaho', 'Washington', 'Alaska'], 'geography', '2025'),
('Name one state that borders Mexico.', ARRAY['California', 'Arizona', 'New Mexico', 'Texas'], 'geography', '2025'),
('What is the capital of the United States?', ARRAY['Washington, D.C.'], 'geography', '2025'),
('Where is the Statue of Liberty?', ARRAY['New York (Harbor)', 'Liberty Island', 'New Jersey', 'near New York City', 'on the Hudson (River)'], 'geography', '2025'),
('Name one of the largest states by area.', ARRAY['Alaska', 'Texas', 'California'], 'geography', '2025'),
('What is the tallest mountain in the United States?', ARRAY['Denali', 'Mount McKinley'], 'geography', '2025'),

-- SYMBOLS
('Why does the flag have 13 stripes?', ARRAY['because there were 13 original colonies', 'because the stripes represent the original colonies'], 'symbols', '2025'),
('Why does the flag have 50 stars?', ARRAY['because there is one star for each state', 'because each star represents a state', 'because there are 50 states'], 'symbols', '2025'),
('What is the name of the national anthem?', ARRAY['The Star-Spangled Banner'], 'symbols', '2025'),
('What does the bald eagle represent?', ARRAY['the United States', 'freedom', 'the national symbol of the United States'], 'symbols', '2025'),
('Who wrote the Star-Spangled Banner?', ARRAY['Francis Scott Key'], 'symbols', '2025'),

-- HOLIDAYS
('When do we celebrate Independence Day?', ARRAY['July 4'], 'holidays', '2025'),
('Name two national federal holidays.', ARRAY['New Year''s Day', 'Martin Luther King Jr. Day', 'Presidents'' Day', 'Memorial Day', 'Juneteenth', 'Independence Day', 'Labor Day', 'Columbus Day', 'Veterans Day', 'Thanksgiving', 'Christmas'], 'holidays', '2025'),
('What is the significance of Thanksgiving?', ARRAY['a holiday to give thanks', 'celebrates the harvest', 'commemorates the Pilgrims'' feast with Native Americans'], 'holidays', '2025'),
('When is Memorial Day?', ARRAY['the last Monday in May'], 'holidays', '2025'),
('What is the purpose of Veterans Day?', ARRAY['to honor people who have served in the U.S. military', 'to honor American veterans'], 'holidays', '2025'),
('What is Juneteenth?', ARRAY['a holiday celebrating the end of slavery', 'a federal holiday on June 19th commemorating emancipation'], 'holidays', '2025'),

-- INTEGRATED CIVICS
('What is the capital of the United States?', ARRAY['Washington, D.C.'], 'integrated_civics', '2025'),
('Who is the current President of the United States?', ARRAY['Joe Biden', 'Biden'], 'integrated_civics', '2025'),
('What are the three branches of government?', ARRAY['legislative, executive, and judicial'], 'integrated_civics', '2025'),
('What is the supreme law of the United States?', ARRAY['the Constitution'], 'integrated_civics', '2025'),
('What freedom does the First Amendment guarantee?', ARRAY['freedom of speech, religion, press, assembly, and petition'], 'integrated_civics', '2025');
